"""Export notebook code cells into a plain Python file for regression tests.

This module owns conversion of notebook code-cell source into a Python export.
It does not own analysis logic or notebook mutation.
It depends on the notebook JSON structure used by Jupyter.
Important constraints:
- Notebook-only commands such as magics and shell escapes must not execute in tests.
- Malformed notebook structure should fail loudly instead of producing partial exports.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_NOTEBOOK_PATH = REPO_ROOT / "blankTemplate.ipynb"
DEFAULT_OUTPUT_PATH = REPO_ROOT / "tests" / "notebook_code.py"
NOTEBOOK_LINE_PREFIXES = ("%", "!", "?")


def load_notebook(notebook_path: Path) -> dict:
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    if not isinstance(notebook, dict):
        raise ValueError("Notebook root must be a JSON object.")
    if not isinstance(notebook.get("cells"), list):
        raise ValueError("Notebook JSON must contain a 'cells' list.")
    return notebook


def normalise_source_lines(source: object) -> list[str]:
    if isinstance(source, str):
        return source.splitlines(keepends=True)
    if isinstance(source, list):
        normalised_lines: list[str] = []
        for line in source:
            if not isinstance(line, str):
                raise TypeError("Notebook cell source lines must be strings.")
            normalised_lines.append(line if line.endswith("\n") else f"{line}\n")
        return normalised_lines
    raise TypeError("Notebook cell source must be a string or list of strings.")


def is_notebook_only_line(line: str) -> bool:
    stripped = line.lstrip()
    return stripped.startswith(NOTEBOOK_LINE_PREFIXES) or "get_ipython(" in stripped


def comment_out_line(line: str) -> str:
    stripped_newline = line.rstrip("\n")
    if not stripped_newline:
        return "#\n"
    return f"# {stripped_newline}\n"


def sanitise_cell_source(lines: list[str]) -> list[str]:
    first_content_line = next((line.lstrip() for line in lines if line.strip()), "")
    if first_content_line.startswith("%%"):
        # Cell magics change how the whole cell executes, so keep the source
        # visible in the export but comment out every line to avoid execution.
        return [comment_out_line(line) for line in lines]

    sanitised_lines: list[str] = []
    for line in lines:
        if is_notebook_only_line(line):
            sanitised_lines.append(comment_out_line(line))
            continue
        sanitised_lines.append(line)
    return sanitised_lines


def iter_code_cells(notebook: dict) -> list[tuple[int, int, list[str]]]:
    code_cells: list[tuple[int, int, list[str]]] = []
    code_cell_index = 0

    for notebook_cell_index, cell in enumerate(notebook.get("cells", []), start=1):
        if cell.get("cell_type") != "code":
            continue

        code_cell_index += 1
        source_lines = normalise_source_lines(cell.get("source", []))
        code_cells.append((notebook_cell_index, code_cell_index, source_lines))

    return code_cells


def render_python_export(notebook_path: Path) -> str:
    notebook = load_notebook(notebook_path)
    code_cells = iter_code_cells(notebook)

    output_lines = [
        '"""Code extracted from the project notebook for regression testing.\n',
        "\n",
        f"Source notebook: {notebook_path.name}\n",
        "Generated by: scripts/extract_notebook_code.py\n",
        '"""\n',
        "\n",
    ]

    for notebook_cell_index, code_cell_index, source_lines in code_cells:
        output_lines.append(
            f"# %% Notebook cell {notebook_cell_index} (code cell {code_cell_index})\n"
        )
        sanitised_lines = sanitise_cell_source(source_lines)

        if sanitised_lines:
            output_lines.extend(sanitised_lines)
            if sanitised_lines[-1].strip():
                output_lines.append("\n")
        else:
            output_lines.append("pass\n\n")

    return "".join(output_lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract code cells from a notebook into a plain Python file."
    )
    parser.add_argument(
        "--notebook",
        type=Path,
        default=DEFAULT_NOTEBOOK_PATH,
        help=f"Notebook to extract from. Defaults to {DEFAULT_NOTEBOOK_PATH.name}.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=(
            "Python file to write. "
            f"Defaults to {DEFAULT_OUTPUT_PATH.relative_to(REPO_ROOT).as_posix()}."
        ),
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the extracted code to stdout instead of writing a file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    notebook_path = args.notebook.resolve()
    export_text = render_python_export(notebook_path)

    if args.stdout:
        try:
            sys.stdout.write(export_text)
        except UnicodeEncodeError:
            # Fall back to UTF-8 bytes when the active terminal encoding cannot
            # represent notebook text such as mathematical symbols.
            sys.stdout.buffer.write(export_text.encode("utf-8"))
        return 0

    output_path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(export_text, encoding="utf-8")
    print(
        "Extracted notebook code "
        f"from {notebook_path} to {output_path}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
